### ISSUE TITLE
Fails on empty lists or objects

### ISSUE THREAD

**Issue by bastianbowe2000** [fiatjaf/jiq#13]
$ echo '{}'|jiq
    panic: runtime error: index out of range
    
    goroutine 1 [running]:
    github.com/fiatjaf/jiq.(*Engine).makeCandidates(0xc4200ae000)
    	/home/babowe/go/src/github.com/fiatjaf/jiq/engine.go:195 +0x56c
    github.com/fiatjaf/jiq.(*Engine).Run(0xc4200ae000, 0x0)
    	/home/babowe/go/src/github.com/fiatjaf/jiq/engine.go:70 +0x13e
    main.run(0xc4200ae000, 0xc42000c000, 0xc42000e1b0)
    	/home/babowe/go/src/github.com/fiatjaf/jiq/cmd/jiq/jiq.go:53 +0x2f
    main.main()
    	/home/babowe/go/src/github.com/fiatjaf/jiq/cmd/jiq/jiq.go:49 +0x22f

**Comment by aesyondu** [comment]
```shell
$ echo '[]' | jiq

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/fiatjaf/jiq.(*Engine).makeCandidates(0xc0000d2000)
	/Users/aes/go/src/github.com/fiatjaf/jiq/engine.go:201 +0x560
github.com/fiatjaf/jiq.(*Engine).Run(0xc0000d2000, 0x0)
	/Users/aes/go/src/github.com/fiatjaf/jiq/engine.go:70 +0x118
main.run(0xc0000d2000, 0xc00008c000, 0xc000092010)
	/Users/aes/go/src/github.com/fiatjaf/jiq/cmd/jiq/jiq.go:53 +0x32
main.main()
	/Users/aes/go/src/github.com/fiatjaf/jiq/cmd/jiq/jiq.go:49 +0x14b
```

I guess fixing this simple bug would be a good excuse to learn go?

**Comment by fiatjaf** [comment]
Probably not, too irrelevant, and yet confusing.

Fixed in https://github.com/fiatjaf/jiq/commit/b24f06fabb766059db624dd8bc41ef1ff4d208ad
